### ISSUE TITLE
Error "monotonic" when I launch the program

### ISSUE THREAD

**Issue by nakiot** [jeffreydwalter/arlo#136]
Please answer these questions before submitting your issue. Thanks!

### What version of Python are you using (`python -V`)?

pi@raspberrypi:~ $ python -V
Python 2.7.16
pi@raspberrypi:~ $ python3 -V
Python 3.7.3

### What operating system and processor architecture are you using (`python -c 'import platform; print(platform.uname());'`)?

pi@raspberrypi:~ $ python -c 'import platform; print(platform.uname());'
('Linux', 'raspberrypi', '4.19.75-v7+', '#1270 SMP Tue Sep 24 18:45:11 BST 2019', 'armv7l', '')

### Which Python packages do you have installed (run the `pip freeze` or `pip3 freeze` command and paste output)?

```
pi@raspberrypi:~ $ sudo pip freeze
arandr==0.1.9
arlo==1.2.30
asn1crypto==0.24.0
automationhat==0.2.0
blinker==1.4
blinkt==0.1.2
buttonshim==0.0.2
Cap1xxx==0.1.3
certifi==2018.8.24
chardet==3.0.4
Click==7.0
colorama==0.3.7
colorzero==1.1
configparser==3.5.0b2
cookies==2.2.1
cryptography==2.6.1
drumhat==0.1.0
entrypoints==0.3
enum34==1.1.6
envirophat==1.0.0
ExplorerHAT==0.4.2
Flask==1.0.2
fourletterphat==0.1.0
funcsigs==1.0.2
gpiozero==1.5.1
gyp==0.1
idna==2.6
ipaddress==1.0.17
itsdangerous==0.24
Jinja2==2.10
keyring==17.1.1
keyrings.alt==3.1.1
MarkupSafe==1.1.0
mcpi==0.1.1
microdotphat==0.2.1
mock==2.0.0
monotonic==1.5
mote==0.0.4
motephat==0.0.2
numpy==1.16.2
oauthlib==2.1.0
olefile==0.46
pantilthat==0.0.7
pbr==4.2.0
phatbeat==0.1.1
pianohat==0.1.0
picamera==1.13
picraft==1.0
piglow==1.2.4
pigpio==1.44
Pillow==5.4.1
pyarlo==0.2.3
pycairo==1.16.2
pycrypto==2.6.1
pyflakes==2.0.0
pygame==1.9.4.post1
PyGObject==3.30.4
pyinotify==0.9.6
PyJWT==1.7.0
pyOpenSSL==19.0.0
pyserial==3.4
PySocks==1.7.1
pyxdg==0.25
rainbowhat==0.1.0
requests==2.21.0
requests-oauthlib==1.0.0
responses==0.9.0
RPi.GPIO==0.7.0
RTIMULib==7.2.1
scrollphat==0.0.7
scrollphathd==1.2.1
SecretStorage==2.3.1
sense-emu==1.1
sense-hat==2.2.0
simplejson==3.16.0
six==1.12.0
skywriter==0.0.7
sn3218==1.2.7
spidev==3.3
sseclient==0.0.22
sseclient-py==1.7
touchphat==0.0.1
twython==3.7.0
unicornhathd==0.0.4
urllib3==1.24.1
Werkzeug==0.14.1

pi@raspberrypi:~ $ sudo pip3 freeze
appdirs==1.4.3
asn1crypto==0.24.0
astroid==2.1.0
asttokens==1.1.13
automationhat==0.2.0
beautifulsoup4==4.7.1
blinker==1.4
blinkt==0.1.2
buttonshim==0.0.2
Cap1xxx==0.1.3
certifi==2018.8.24
chardet==3.0.4
Click==7.0
colorama==0.3.7
colorzero==1.1
cookies==2.2.1
cryptography==2.6.1
cycler==0.10.0
decorator==4.3.0
docutils==0.14
drumhat==0.1.0
entrypoints==0.3
envirophat==1.0.0
ExplorerHAT==0.4.2
Flask==1.0.2
fourletterphat==0.1.0
gpiozero==1.5.1
guizero==0.6.0
html5lib==1.0.1
idna==2.6
ipykernel==4.9.0
ipython==5.8.0
ipython-genutils==0.2.0
isort==4.3.4
itsdangerous==0.24
jedi==0.13.2
Jinja2==2.10
jupyter-client==5.2.3
jupyter-core==4.4.0
keyring==17.1.1
keyrings.alt==3.1.1
kiwisolver==1.0.1
lazy-object-proxy==1.3.1
logilab-common==1.4.2
lxml==4.3.2
MarkupSafe==1.1.0
matplotlib==3.0.2
mccabe==0.6.1
microdotphat==0.2.1
mote==0.0.4
motephat==0.0.2
mypy==0.670
mypy-extensions==0.4.1
nudatus==0.0.4
numpy==1.16.2
oauthlib==2.1.0
olefile==0.46
pantilthat==0.0.7
parso==0.3.1
pexpect==4.6.0
pgzero==1.2
phatbeat==0.1.1
pianohat==0.1.0
picamera==1.13
pickleshare==0.7.5
picraft==1.0
piglow==1.2.4
pigpio==1.44
Pillow==5.4.1
prompt-toolkit==1.0.15
psutil==5.5.1
pyarlo==0.2.4
pycairo==1.16.2
pycodestyle==2.4.0
pycrypto==2.6.1
pyflakes==2.0.0
pygame==1.9.4.post1
Pygments==2.3.1
PyGObject==3.30.4
pyinotify==0.9.6
PyJWT==1.7.0
pylint==2.2.2
pyOpenSSL==19.0.0
pyparsing==2.2.0
pyserial==3.4
python-apt==1.8.4
python-dateutil==2.7.3
pyxdg==0.25
pyzmq==17.1.2
qtconsole==4.3.1
rainbowhat==0.1.0
requests==2.21.0
requests-oauthlib==1.0.0
responses==0.9.0
roman==2.0.0
RPi.GPIO==0.7.0
RTIMULib==7.2.1
scrollphat==0.0.7
scrollphathd==1.2.1
SecretStorage==2.3.1
semver==2.0.1
Send2Trash==1.5.0
sense-emu==1.1
sense-hat==2.2.0
simplegeneric==0.8.1
simplejson==3.16.0
six==1.12.0
skywriter==0.0.7
sn3218==1.2.7
soupsieve==1.8
spidev==3.3
sseclient-py==1.7
ssh-import-id==5.7
thonny==3.2.0
tornado==5.1.1
touchphat==0.0.1
traitlets==4.3.2
twython==3.7.0
typed-ast==1.3.1
uflash==1.2.4
unicornhathd==0.0.4
urllib3==1.24.1
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.14.1
wrapt==1.10.11


```

### Which version of ffmpeg are you using (`ffmpeg -version`)?
```
pi@raspberrypi:~ $ ffmpeg -version
ffmpeg version 4.1.4-1+rpt1~deb10u1 Copyright (c) 2000-2019 the FFmpeg developers
built with gcc 8 (Raspbian 8.3.0-6+rpi1)

```

### Which Arlo hardware do you have (camera types - [Arlo, Pro, Q, etc.], basestation model, etc.)?

Arlo Pro 2

### What did you do?

If possible, provide the steps you took to reproduce the issue. 
A complete runnable program is good. (don't include your user/password or any sensitive info)
```
I've installed arlo:
pi@raspberrypi:~ $ sudo pip install arlo
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: arlo in /usr/local/lib/python2.7/dist-packages (1.2.30)
Requirement already satisfied: sseclient==0.0.22 in /usr/local/lib/python2.7/dist-packages (from arlo) (0.0.22)
Requirement already satisfied: monotonic in /usr/local/lib/python2.7/dist-packages (from arlo) (1.5)
Requirement already satisfied: PySocks in /usr/local/lib/python2.7/dist-packages (from arlo) (1.7.1)
Requirement already satisfied: requests in /usr/lib/python2.7/dist-packages (from arlo) (2.21.0)
Requirement already satisfied: six in /usr/lib/python2.7/dist-packages (from sseclient==0.0.22->arlo) (1.12.0)


Then copy/past your program and changed username/password
Launch the program with Thonny python IDE


```

### What did you expect to see?
```
No error I guess
```

### What did you see instead?
```
>>> %Run program.py
Traceback (most recent call last):
  File "/home/pi/Desktop/prog/arlo-master/program.py", line 1, in <module>
    from arlo import Arlo
  File "/home/pi/Desktop/prog/arlo-master/arlo.py", line 22, in <module>
    from eventstream import EventStream
  File "/home/pi/Desktop/prog/arlo-master/eventstream.py", line 17, in <module>
    import monotonic
ModuleNotFoundError: No module named 'monotonic'
```

### Does this issue reproduce with the latest release?

Yes

Thanks a lot for your help

**Comment by jeffreydwalter** [comment]
I don't know what the Thonny Python IDE is, but I assume it's using `python3` instead of `python2` and you don't have the `arlo` packages and it's dependencies installed for `python3`.
