### ISSUE TITLE
sseclient.py - version 0.0.24?

### ISSUE THREAD

**Issue by JavaWiz1** [jeffreydwalter/arlo#142]
Please answer these questions before submitting your issue. Thanks!

### What version of Python are you using (`python -V`)?
Python 3.7

### What operating system and processor architecture are you using (`python -c 'import platform; print(platform.uname());'`)?
Basically multi-platform - windows, Linux, Raspbian...

### Which Python packages do you have installed (run the `pip freeze` or `pip3 freeze` command and paste output)?
```  Running under the Kodi environment

### Which version of ffmpeg are you using (`ffmpeg -version`)?
NA - Using kodi renderers

### Which Arlo hardware do you have (camera types - [Arlo, Pro, Q, etc.], basestation model, etc.)?
Not camera specific...

### What did you do?
Appears Kodi platform has upgraded sseclient package to 0,0,24.  Is there any chance your Arlo code could be updated to use this version?

If possible, provide the steps you took to reproduce the issue. 
A complete runnable program is good. (don't include your user/password or any sensitive info)
Simply have to install the Arlo Streamer plugin in Kodi.

### What did you expect to see?
A successful call to getCameraState()

### What did you see instead?
ERROR: Exception in thread EventStream:
          Traceback (most recent call last):
            File "C:\Program Files (x86)\Kodi\system\python\Lib\threading.py", line 801, in __bootstrap_inner
              self.run()
            File "C:\Program Files (x86)\Kodi\system\python\Lib\threading.py", line 754, in run
              self.__target(*self.__args, **self.__kwargs)
            File "C:\Users\a_dam\AppData\Roaming\Kodi\addons\script.module.arlo\lib\arlo.py", line 181, in QueueEvents
              for event in event_stream:
            File "C:\Users\a_dam\AppData\Roaming\Kodi\addons\script.module.sseclient\lib\sseclient.py", line 92, in __next__
              next_chunk = next(self.resp_iterator)
            File "C:\Users\a_dam\AppData\Roaming\Kodi\addons\script.module.sseclient\lib\sseclient.py", line 74, in generate
              chunk = self.resp.raw.read(self.chunk_size)
            File "C:\Users\a_dam\AppData\Roaming\Kodi\addons\script.module.urllib3\lib\urllib3\response.py", line 529, in read
              raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
            File "C:\Program Files (x86)\Kodi\system\python\Lib\contextlib.py", line 35, in __exit__
              self.gen.throw(type, value, traceback)
            File "C:\Users\a_dam\AppData\Roaming\Kodi\addons\script.module.urllib3\lib\urllib3\response.py", line 443, in _error_catcher
              raise ProtocolError("Connection broken: %r" % e, e)

### Does this issue reproduce with the latest release?

yes

**Comment by jeffreydwalter** [comment]
@JavaWiz1 no chance until 0.0.24 isn't completely broken. https://github.com/btubbs/sseclient/issues

Feel free to play around with 0.0.24 and this library. If they work well together for you, let me know and I'll consider revisiting it.
