### ISSUE TITLE
'Origin': f'https://{self.BASE_URL}', SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by raymindware** [jeffreydwalter/arlo#191]
Hi All,

Just install the  libraries, then try to run test code, I got these SyntaxError: invalid syntax.

Any idea?

Thanks

Ray 

Please answer these questions before submitting your issue. Thanks!

### What version of Python are you using (`python -V`)?

Python 2.7.12
### What operating system and processor architecture are you using (`python -c 'import platform; print(platform.uname());'`)?
('Linux', 'fax2', '4.4.0-131-generic', '#157-Ubuntu SMP Thu Jul 12 15:51:36 UTC 2018', 'x86_64', 'x86_64')

### Which Python packages do you have installed (run the `pip freeze` or `pip3 freeze` command and paste output)?
```arlo==1.2.59
certifi==2021.10.8
chardet==4.0.0
enum34==1.1.10
google-api-core==2.7.1
google-api-python-client==2.42.0
google-auth==2.6.2
google-auth-httplib2==0.1.0
google-auth-oauthlib==0.5.1
googleapis-common-protos==1.56.0
httplib2==0.20.4
idna==2.10
monotonic==1.6
oauthlib==3.2.0
pickle-mixin==1.0.2
protobuf==3.19.4
pyasn1==0.4.8
pyasn1-modules==0.2.8
pyparsing==2.4.7
PySocks==1.7.1
requests==2.27.1
requests-oauthlib==1.3.1
rsa==4.5
six==1.16.0
sseclient==0.0.22
UNKNOWN==0.0.0
uritemplate==4.1.1
urllib3==1.24
Paste your ouptut here
```

### Which version of ffmpeg are you using (`ffmpeg -version`)?
```
Paste your output here
```

### Which Arlo hardware do you have (camera types - [Arlo, Pro, Q, etc.], basestation model, etc.)?
Arlo Pro 4

### What did you do?

If possible, provide the steps you took to reproduce the issue. 
A complete runnable program is good. (don't include your user/password or any sensitive info)
```
Paste your ouptut here
```

### What did you expect to see?
```
Paste your ouptut here
```

### What did you see instead?
```
Paste your ouptut here

root@fax2:/home/ray# python ./test.py
Traceback (most recent call last):
  File "./test.py", line 1, in <module>
    from arlo import Arlo
  File "/usr/local/lib/python2.7/dist-packages/arlo.py", line 144
    'Origin': f'https://{self.BASE_URL}',
                                       ^
SyntaxError: invalid syntax

### Does this issue reproduce with the latest release?

**Comment by raymindware** [comment]
Sorry, Need python 3.6
