### ISSUE TITLE
Exception trying to login to Arlo

### ISSUE THREAD

**Issue by imopen** [jeffreydwalter/arlo#33]
Hello @jeffreydwalter 
I'm having issue while connecting to Arlo, simple code:

```
arlo = Arlo(USERNAME, PASSWORD)
my_devices = arlo.GetDevices()
for i in my_devices:
    print "\n"+json.dumps(i, sort_keys=True, indent=4)+"\n"

arlo.Logout()

```

I'm obtaining:

```
2017/12/13 12:38:33 | DEBUG | Starting new HTTPS connection (1): arlo.netgear.com
Traceback (most recent call last):
  File "./arlo_test.py", line 24, in <module>
    arlo = Arlo(USERNAME, PASSWORD)
  File "/root/arlo_autoarm/Arlo.py", line 130, in __init__
    self.Login(username, password)
  File "/root/arlo_autoarm/Arlo.py", line 196, in Login
    body = self.request.post('https://arlo.netgear.com/hmsweb/login/v2', {'email': self.username, 'password': self.password})
  File "/root/arlo_autoarm/Arlo.py", line 121, in post
    return self._request(url, 'POST', params, headers)
  File "/root/arlo_autoarm/Arlo.py", line 104, in _request
    r = self.session.post(url, json=params, headers=headers)
  File "/home/omar/.local/lib/python2.7/site-packages/requests/sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/omar/.local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/omar/.local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/omar/.local/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='arlo.netgear.com', port=443): Max retries exceeded with url: /hmsweb/login/v2 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f266e1d7fd0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))

```
But using the same USERNAME and PASSWORD from web browser it does login.

Can you help me?

Thanks in advance,
imopen

**Comment by imopen** [comment]
Hello @jeffreydwalter 
forget it, I had issue with my resolv.conf file. I've sorted out it.
Sorry for the fake issue, I close it.

Best regards,
imopen
