### ISSUE TITLE
Example code won't run, claiming that monotonic is not installed

### ISSUE THREAD

**Issue by ghost** [jeffreydwalter/arlo#67]
Thanks for making and sharing this code. I've recently installed an arlo system and I'm interested in contributing to your project, but I'm relatively new to python programming, so I may be doing something wrong here. In any case, at this point, I think it's a problem with the code and not with me.

### What version of Python are you using (`python -V`)?
```
$ python -V
Python 2.7.15

```
### What operating system and processor architecture are you using (`python -c 'import platform; print(platform.uname());'`)?
```
$ python -c 'import platform; print(platform.uname());'
('Darwin', 'tui', '17.5.0', 'Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64', 'x86_64', 'i386')
```

### Which Python packages do you have installed (run the `pip freeze` or `pip3 freeze` command and paste output)?
```
$ pip freeze
appdirs==1.4.3
asn1crypto==0.24.0
attrs==17.4.0
Automat==0.6.0
Beaker==1.9.1
certifi==2018.4.16
cffi==1.11.5
chardet==3.0.4
click==6.7
constantly==15.1.0
cryptography==2.2.2
Cython==0.28.2
enum34==1.1.6
funcsigs==1.0.2
gnureadline==6.3.3
graphviz==0.8
hyperlink==17.3.0
idna==2.6
incremental==17.5.0
ipaddress==1.0.22
Mako==1.0.7
MarkupSafe==0.23
nose==1.3.7
numpy==1.14.2
packaging==17.1
pyasn1==0.4.2
pyasn1-modules==0.0.7
pycairo==1.15.4
pycparser==2.18
pygame==1.9.3
pyOpenSSL==17.5.0
pyparsing==2.2.0
python-libtorrent==1.1.7
pyxdg==0.25
service-identity==17.0.0
six==1.11.0
Twisted==17.9.0
zope.interface==4.4.1
```

### Which Arlo hardware do you have (camera types - [Arlo, Pro, Q, etc.], basestation model, etc.)?
Arlo

### What did you do?

```
$ sudo port install python27
$ sudo port install py27-pip
$ sudo port select --set pip pip27
$ git clone https://github.com/jeffreydwalter/arlo.git
$ pip install monotonic 
$ pip install requests
$ pip install sseclient
$ pip show monotonic
You are using pip version 10.0.0, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command. # I think I can ignore this?
$ pip show requests
You are using pip version 10.0.0, however version 10.0.1 is available.
$ pip show sseclient
You are using pip version 10.0.0, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.You should consider upgrading via the 'pip install --upgrade pip' command.
$ pip uninstall monotonic requests sseclient 
Skipping requests as it is not installed.
Skipping monotonic as it is not installed.
Skipping sseclient as it is not installed.
You are using pip version 10.0.0, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
$ python myarlo.py
```
Then I just created a local file myarlo.py by copying and pasting the example I found at https://github.com/jeffreydwalter/arlo and replacing my username and password for the ones I found in that example code.

### What did you expect to see?

Code runs (download videos from library and delete them from library?).

### What did you see instead?

```
$ python myarlo.py 
Traceback (most recent call last):
  File "myarlo.py", line 1, in <module>
    from Arlo import Arlo
  File "/Users/alpha/sources/arlo/Arlo.py", line 24, in <module>
    import monotonic
ImportError: No module named monotonic
```

### Does this issue reproduce with the latest release?

Yes

**Comment by jeffreydwalter** [comment]
If you look at the output of your `pip freeze` command, you can see none of the packages you tried to install were installed. You might try just installing the arlo library via pip, so: 
```
pip install arlo
```

If that doesn't work, then you might try upgrading your pip package.

**Comment by ghost** [comment]
In case you're wondering, the reason I did `pip uninstall monotonic requests sseclient ` was not to uninstall those modules, but instead to show explicitly that despite having installed them on lines above, pip list and pip freeze do not list them as being installed. The pip uninstall command was merely to get pip to report this in explicit terms.

Oh, and about `$ pip install arlo `, I did actually do that. Just forgot to list it here. Sorry...

**Comment by jeffreydwalter** [comment]
Try this command `sudo python -m ensurepip` or `sudo easy_install pip`.

**Comment by ghost** [comment]
```
$ pip install arlo
Collecting arlo
  Using cached https://files.pythonhosted.org/packages/a6/ef/05e4948478edccdb63bb6d033da8d5df6e484415f7f3b265060b1d9be2c2/arlo-1.1.2-py2.py3-none-any.whl
Collecting monotonic (from arlo)
  Using cached https://files.pythonhosted.org/packages/ac/aa/063eca6a416f397bd99552c534c6d11d57f58f2e94c14780f3bbf818c4cf/monotonic-1.5-py2.py3-none-any.whl
Collecting PySocks (from arlo)
  Using cached https://files.pythonhosted.org/packages/53/12/6bf1d764f128636cef7408e8156b7235b150ea31650d0260969215bb8e7d/PySocks-1.6.8.tar.gz
Collecting requests (from arlo)
  Using cached https://files.pythonhosted.org/packages/49/df/50aa1999ab9bde74656c2919d9c0c085fd2b3775fd3eca826012bef76d8c/requests-2.18.4-py2.py3-none-any.whl
Collecting sseclient (from arlo)
  Using cached https://files.pythonhosted.org/packages/e3/fd/29f3bb9beaabf36fe61ff08463e9a2c49c54b9cfee20eceafd5c922e790a/sseclient-0.0.19.tar.gz
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from requests->arlo) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from requests->arlo) (2018.4.16)
Collecting urllib3<1.23,>=1.21.1 (from requests->arlo)
  Using cached https://files.pythonhosted.org/packages/63/cb/6965947c13a94236f6d4b8223e21beb4d576dc72e8130bd7880f600839b8/urllib3-1.22-py2.py3-none-any.whl
Requirement already satisfied: idna<2.7,>=2.5 in /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from requests->arlo) (2.6)
Requirement already satisfied: six in /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from sseclient->arlo) (1.11.0)
Installing collected packages: monotonic, PySocks, urllib3, requests, sseclient, arlo

You are using pip version 10.0.0, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
tui:arlo alpha$ pip freeze|grep arlo
You are using pip version 10.0.0, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by jeffreydwalter** [comment]
Why did you have to install Python anyway? Python is installed on Mac out of the box.

**Comment by ghost** [comment]
In the past I've found that Mac python differs in some important ways from more standard python (that I found in the Macports project).

**Comment by ghost** [comment]
```
$ python -m ensurepip
Requirement already satisfied: setuptools in /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
Requirement already satisfied: pip in /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages

```

**Comment by ghost** [comment]
If I do `$ sudo python -m ensurepip` , I get an error:

```
The directory '/Users/alpha/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/alpha/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
```

It seems like this is attempting to verify that the superuser owns these directories, when I'd rather have the non-superuser own them. Why use sudo here?

**Comment by jeffreydwalter** [comment]
you need `sudo -H python -m ensurepip`

**Comment by jeffreydwalter** [comment]
Seems like you have a python version conflict...

Try running pip via python
`python -m pip install arlo`

**Comment by ghost** [comment]
```
$ sudo -H python -m ensurepip
Password:
Requirement already satisfied: setuptools in /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
Requirement already satisfied: pip in /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
tui:sources alpha$ pip show sseclient
You are using pip version 10.0.0, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
tui:sources alpha$ 
tui:sources alpha$ pip install monotonic 
Collecting monotonic
  Using cached https://files.pythonhosted.org/packages/ac/aa/063eca6a416f397bd99552c534c6d11d57f58f2e94c14780f3bbf818c4cf/monotonic-1.5-py2.py3-none-any.whl
Installing collected packages: monotonic

You are using pip version 10.0.0, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
tui:sources alpha$ pip show monotonic
You are using pip version 10.0.0, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by ghost** [comment]
```
$ python -m pip install arlo
Collecting arlo
  Using cached https://files.pythonhosted.org/packages/a6/ef/05e4948478edccdb63bb6d033da8d5df6e484415f7f3b265060b1d9be2c2/arlo-1.1.2-py2.py3-none-any.whl
Collecting monotonic (from arlo)
  Using cached https://files.pythonhosted.org/packages/ac/aa/063eca6a416f397bd99552c534c6d11d57f58f2e94c14780f3bbf818c4cf/monotonic-1.5-py2.py3-none-any.whl
Collecting PySocks (from arlo)
  Using cached https://files.pythonhosted.org/packages/53/12/6bf1d764f128636cef7408e8156b7235b150ea31650d0260969215bb8e7d/PySocks-1.6.8.tar.gz
Collecting requests (from arlo)
  Using cached https://files.pythonhosted.org/packages/49/df/50aa1999ab9bde74656c2919d9c0c085fd2b3775fd3eca826012bef76d8c/requests-2.18.4-py2.py3-none-any.whl
Collecting sseclient (from arlo)
  Using cached https://files.pythonhosted.org/packages/e3/fd/29f3bb9beaabf36fe61ff08463e9a2c49c54b9cfee20eceafd5c922e790a/sseclient-0.0.19.tar.gz
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from requests->arlo) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from requests->arlo) (2018.4.16)
Collecting urllib3<1.23,>=1.21.1 (from requests->arlo)
  Using cached https://files.pythonhosted.org/packages/63/cb/6965947c13a94236f6d4b8223e21beb4d576dc72e8130bd7880f600839b8/urllib3-1.22-py2.py3-none-any.whl
Requirement already satisfied: idna<2.7,>=2.5 in /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from requests->arlo) (2.6)
Requirement already satisfied: six in /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from sseclient->arlo) (1.11.0)
Installing collected packages: monotonic, PySocks, urllib3, requests, sseclient, arlo

You are using pip version 10.0.0, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by jeffreydwalter** [comment]
what does `python -m pip freeze` show?

**Comment by ghost** [comment]
```
$ python -m pip freeze
appdirs==1.4.3
asn1crypto==0.24.0
attrs==17.4.0
Automat==0.6.0
Beaker==1.9.1
certifi==2018.4.16
cffi==1.11.5
chardet==3.0.4
click==6.7
constantly==15.1.0
cryptography==2.2.2
Cython==0.28.2
enum34==1.1.6
funcsigs==1.0.2
gnureadline==6.3.3
graphviz==0.8
hyperlink==17.3.0
idna==2.6
incremental==17.5.0
ipaddress==1.0.22
Mako==1.0.7
MarkupSafe==0.23
nose==1.3.7
numpy==1.14.2
packaging==17.1
pyasn1==0.4.2
pyasn1-modules==0.0.7
pycairo==1.15.4
pycparser==2.18
pygame==1.9.3
pyOpenSSL==17.5.0
pyparsing==2.2.0
python-libtorrent==1.1.7
pyxdg==0.25
service-identity==17.0.0
six==1.11.0
Twisted==17.9.0
zope.interface==4.4.1
You are using pip version 10.0.0, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by jeffreydwalter** [comment]
I really don't know... You have some issues with your python/pip install on your mac. I wish I could help you, but I'm not really an expert on python packaging.

**Comment by ghost** [comment]
I'll keep working on it. Thanks for the suggestions!

**Comment by jeffreydwalter** [comment]
maybe run the `pip install --upgrade pip` command, see what happens.

**Comment by jeffreydwalter** [comment]
Did you ever get this figured out?

**Comment by jeffreydwalter** [comment]
Was thinking about this more, and I bet your problem is related to having multiple python installs.

Something along these lines: 
see: https://stackoverflow.com/questions/26006609/pip-doesnt-show-my-installed-packages
see: https://stackoverflow.com/questions/25276329/cant-load-python-modules-installed-via-pip-from-site-packages-directory
