### ISSUE TITLE
GetModes randomly hangs

### ISSUE THREAD

**Issue by clorteau** [jeffreydwalter/arlo#95]
### What version of Python are you using (`python -V`)?
2.7.13

### What operating system and processor architecture are you using (`python -c 'import platform; print(platform.uname());'`)?
('Linux', 'raspberrypi.lan', '4.14.71-v7+', '#1145 SMP Fri Sep 21 15:38:35 BST 2018', 'armv7l', '')
Running Raspbian on a raspberry pi 3 b+.

### Which Python packages do you have installed (run the `pip freeze` or `pip3 freeze` command and paste output)?
arlo==1.0.9
arrow==0.12.1
backports-abc==0.5
backports.functools-lru-cache==1.5
bitstring==3.1.5
certifi==2018.4.16
chardet==3.0.4
cryptography==1.7.1
enum34==1.1.6
evdev==1.1.2
futures==3.2.0
gpiozero==1.4.1
idna==2.6
ipaddress==1.0.17
keyring==10.1
keyrings.alt==1.3
monotonic==1.4
numpy==1.12.1
picamera==1.13
Pillow==4.0.0
praw==5.4.0
prawcore==0.14.0
pyasn1==0.1.9
pycrypto==2.6.1
pygobject==3.22.0
pymongo==3.4.0
pyOpenSSL==16.2.0
PySocks==1.6.8
python-dateutil==2.7.2
pyxdg==0.25
PyYAML==3.12
requests==2.18.4
RPi.GPIO==0.6.4
SecretStorage==2.3.1
singledispatch==3.4.0.3
six==1.11.0
speedtest-cli==1.0.0
spidev==3.3
sseclient==0.0.19
tornado==5.0.2
update-checker==0.16
urllib3==1.22

### Which Arlo hardware do you have (camera types - [Arlo, Pro, Q, etc.], basestation model, etc.)?
Arlo

### What did you do?
I'm running the following script: https://github.com/clorteau/armdisarmarlo/blob/master/monitor.py
On lines 153 and 67 you can see a call to Arlo.GetModes. It sometimes hang for apparently forever (I have let it stay stuck for hours). I tried adding a timer that refreshes the connection token every 10 minutes but that doesn't help.

### What did you expect to see?
I would expect the call to return or at least throw an exception or an error message. Instead, literally nothing happens. That call sometimes simply never returns.

### What did you see instead?
Nothing; sometimes the call simply doesn't return.

### Does this issue reproduce with the latest release?
I'm using the latest release.
Edit: I just updated to 1.1.8. I'll report back.

**Comment by clorteau** [comment]
I just upgraded my Arlo library to 1.1.8. I'll report back with results.

**Comment by jsm174** [comment]
This seems similar to my issue #93.

**Comment by jeffreydwalter** [comment]
@clorteau this is most certainly the same type of issue as #93. Most likely, I won't have time to look into this until the weekend, but I will definitely dig in.

**Comment by clorteau** [comment]
Great, thanks for looking into it. For what it's worth, I have let the script run all night after upgrading to 1.1.8 and it still hasn't froze.

**Comment by jeffreydwalter** [comment]
Great! Glad to hear that. Keep me posted.

**Comment by clorteau** [comment]
Well, it's been running flawlessly for 2 nights and a day now. So false alarm I guess, my bad!

If I just may venture a suggestion maybe in the readme at https://github.com/jeffreydwalter/arlo state that "pip install Arlo" gets you an outdated version and that "pip install git+https://github.com/jeffreydwalter/arlo" will give you the latest.

Anyway thank you for the support and the library that's very useful.

**Comment by jeffreydwalter** [comment]
Glad to hear it's working for you.

`pip install arlo` does NOT get you an outdated version. It gets the latest stable release version from pypi.

**Comment by clorteau** [comment]
Actually I take that back; it has been happening several times today. So I can now answer "Does this issue reproduce with the latest release?" as "Yes".

Anything I can do to help? I don't mind editing the source to add some debugging outputs.

Is that of any use? It appeared 26 seconds before another freeze:

`Exception in thread EventStream:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in                  __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in                  run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Arlo.py"                 , line 295, in QueueEvents
    self.event_streams[basestation_id].Disconnect()
  File "/usr/local/lib/python2.7/dist-packages/Arlo.py"                 , line 100, in Disconnect
    self.Unregister()
  File "/usr/local/lib/python2.7/dist-packages/Arlo.py"                 , line 120, in Unregister
    if self.heartbeat_thread != threading.current_threa                 d():
AttributeError: 'EventStream' object has no attribute '                 heartbeat_thread'`

**Comment by jeffreydwalter** [comment]
@clorteau just pushed a fix for this issue. Please give it a try when you can and let me know how it goes. Thanks!

**Comment by clorteau** [comment]
Excellent! I'm giving it a shot.

**Comment by clorteau** [comment]
I keep getting this:

> Exception in thread Thread-2:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
>     self.run()
>   File "/usr/lib/python2.7/threading.py", line 754, in run
>     self.__target(*self.__args, **self.__kwargs)
>   File "./monitor.py", line 143, in monitorAndUpdate
>     arlo_armed = arlo.getArmed()
>   File "./monitor.py", line 66, in getArmed
>     status = self.arlo.GetModes(self.basestation)
>   **File "/usr/local/lib/python2.7/dist-packages/Arlo.py", line 505, in GetModes
>     return self.NotifyAndGetResponse(basestation, {"action":"get","resource":"modes","publishResponse":False})
>   File "/usr/local/lib/python2.7/dist-packages/Arlo.py", line 391, in NotifyAndGetResponse
>     self.Subscribe(basestation)
>   File "/usr/local/lib/python2.7/dist-packages/Arlo.py", line 317, in Subscribe
>     self.event_streams[basestation_id].Start()
>   File "/usr/local/lib/python2.7/dist-packages/Arlo.py", line 94, in Start
>     self.event_stream_thread.start()
> AttributeError: 'EventStream' object has no attribute 'event_stream_thread'**


This is in a large _try_ that catches all _Exception_ yet I don't catch it so my thread crashes.

**Comment by jeffreydwalter** [comment]
I don't have my Arlo basestation hooked up right now, so it's impossible for me to test. I increased the message timeout to 10 minutes from 2 minutes. Give the latest release a shot. Thanks.

**Comment by clorteau** [comment]
Same result. Note that I'm getting the exception about immediately.

**Comment by jeffreydwalter** [comment]
Seems like you might be getting an exception when attempting to connect to the event stream. Just pushed another with a print debugging statement. Can you tell me what you see. Thanks! (Sorry for the shitty dev practices. :) )

**Comment by clorteau** [comment]
Lol no worries. But same result i'm afraid.

**Comment by jeffreydwalter** [comment]
Did anything get printed? I had added a print statement.

**Comment by clorteau** [comment]
No really, same thing; this is the entirety of my output - all the prints are from me:

> PID: 24721
> Started
> Input PIN then <Enter> to arm/disarm; '/' then <Enter> to quit; '.' then <Enter> to force refresh
> Exception in thread Thread-2:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
>     self.run()
>   File "/usr/lib/python2.7/threading.py", line 754, in run
>     self.__target(*self.__args, **self.__kwargs)
>   File "./monitor.py", line 144, in monitorAndUpdate
>     arlo_armed = arlo.getArmed()
>   File "./monitor.py", line 67, in getArmed
>     status = self.arlo.GetModes(self.basestation)
>   File "/usr/local/lib/python2.7/dist-packages/Arlo.py", line 505, in GetModes
>     return self.NotifyAndGetResponse(basestation, {"action":"get","resource":"modes","publishResponse":False})
>   File "/usr/local/lib/python2.7/dist-packages/Arlo.py", line 391, in NotifyAndGetResponse
>     self.Subscribe(basestation)
>   File "/usr/local/lib/python2.7/dist-packages/Arlo.py", line 317, in Subscribe
>     self.event_streams[basestation_id].Start()
>   File "/usr/local/lib/python2.7/dist-packages/Arlo.py", line 94, in Start
>     self.event_stream_thread.start()
> AttributeError: 'EventStream' object has no attribute 'event_stream_thread'


And I do have the latest version:

> $ pip freeze | grep arlo
> arlo==1.2.7

**Comment by clorteau** [comment]
@jeffreydwalter If you'd like I created an account with access to my base station so you can run tests. You can email me at [redacted] for the user name and password if you want it.

Edit: Btw I don't see any changes in the last 2 commits besides version number changes:
https://github.com/jeffreydwalter/arlo/commit/a9f9bac8096643cf5fc8ef04898a6511980a47a7
https://github.com/jeffreydwalter/arlo/commit/55c3ac571392107356c24e292323682ca112a62d

**Comment by jeffreydwalter** [comment]
@clorteau thanks for the offer! I REALLY appreciate it. I ended up just hooking my Arlo basestation back up. :) Did some testing and pushed a fix. Please give the latest a try!

**Comment by clorteau** [comment]
Damn, same result again...

Sorry to insist but I still don't see any other change besides a version number change in the last commit: https://github.com/jeffreydwalter/arlo/commit/a655bc9826c067cd94dc1f4d6359b8bf73fe9d6a .

**Comment by jeffreydwalter** [comment]
Ha! I forgot to `git add` the file. lol Sorry! Try now.

**Comment by clorteau** [comment]
Cool. Now I get:

> Exception: Failed to subscribe to eventstream: __init__() got an unexpected keyword argument 'session'

**Comment by jeffreydwalter** [comment]
Okay, great.That exception leads me to believe that you have the wrong version of some package or some conflicting package. Can you paste the output of `pip freeze`?

**Comment by clorteau** [comment]
Here you go:

```
$ pip freeze
arlo==1.2.9
arrow==0.12.1
backports-abc==0.5
backports.functools-lru-cache==1.5
bitstring==3.1.5
certifi==2018.11.29
chardet==3.0.4
cryptography==1.7.1
enum34==1.1.6
evdev==1.1.2
futures==3.2.0
Glances==3.0.2
gpiozero==1.4.1
idna==2.8
ipaddress==1.0.17
keyring==10.1
keyrings.alt==1.3
monotonic==1.4
numpy==1.12.1
picamera==1.13
Pillow==4.0.0
praw==5.4.0
prawcore==0.14.0
psutil==5.4.8
pyarlo==0.2.3
pyasn1==0.1.9
pycrypto==2.6.1
pygobject==3.22.0
pymongo==3.4.0
pyOpenSSL==16.2.0
PySocks==1.6.8
python-dateutil==2.7.2
pyxdg==0.25
PyYAML==3.12
requests==2.21.0
RPi.GPIO==0.6.5
SecretStorage==2.3.1
singledispatch==3.4.0.3
six==1.11.0
speedtest-cli==1.0.0
spidev==3.3
sseclient==0.0.19
sseclient-py==1.7
tornado==5.0.2
update-checker==0.16
urllib3==1.24.1
```

**Comment by jeffreydwalter** [comment]
Yep, here's your problem:
```
sseclient==0.0.19
sseclient-py==1.7
```

Please uninstall `sseclient-py` and try again.

**Comment by clorteau** [comment]
Aaahhh... it even warns in the homepage about it! I thought I checked that but well, evidently no. I don't even know how I got sseclient-py, i'll look at getting rid of it.

**Comment by jeffreydwalter** [comment]
`pip uninstall sseclient-py` should to the trick. I might have to add a check for that in the installer.

**Comment by clorteau** [comment]
Hey much better now! :) So far so good. I'll let it run now to see if the original issue is gone. (According to my first post I did not have it installed originally when I reported the issue)

**Comment by jeffreydwalter** [comment]
Awesome! I don't see `sseclient-py` installed in your original `pip freeze` output. The behavior now should be that the function will return None if it times out. I might change that to have it raise an exception instead...

**Comment by clorteau** [comment]
Cool, my code is already checking for a return of None to refresh the token and re-try, so i'll be able to see if it runs as intended.

Thanks a lot for all the support.

**Comment by jeffreydwalter** [comment]
You got it. Thanks for all your help!

**Comment by clorteau** [comment]
Even though I do get a number of None and can refresh the session token, it still ends up hanging, apparently 30 minutes after the last session refresh. Here's a log of my last run:

```
Jan 25 14:54:01 raspberrypi numpad arming: PID: 18309
Jan 25 14:54:01 raspberrypi numpad arming: Started
Jan 25 16:26:20 raspberrypi numpad arming: Connection error
Jan 25 16:26:22 raspberrypi numpad arming: Refreshed Arlo connection token
Jan 25 17:12:18 raspberrypi numpad arming: Connection error
Jan 25 17:12:21 raspberrypi numpad arming: Refreshed Arlo connection token
Jan 25 17:34:22 raspberrypi numpad arming: Correct PIN entered
Jan 25 18:44:37 raspberrypi numpad arming: Connection error
Jan 25 18:44:39 raspberrypi numpad arming: Refreshed Arlo connection token
Jan 25 18:57:46 raspberrypi numpad arming: Correct PIN entered
Jan 25 19:16:47 raspberrypi numpad arming: Connection error
Jan 25 19:16:49 raspberrypi numpad arming: Refreshed Arlo connection token
```

Then at 19:46:55 my script hangs seemingly forever on the GetArmed and doesn't show any exception or print statement.

**Comment by jeffreydwalter** [comment]
Bummer... I think the problem is that the queue timeout never really happens because of ping messages and other junk in the queue that are getting read. I'll take another stab at it tomorrow.

What is that `Connection error`?

**Comment by clorteau** [comment]
Oh it's just me printing / logging that when I get a None from getModes.

Line 173 of this:
https://github.com/clorteau/armdisarmarlo/blob/master/monitor.py
-- 

Clem

**Comment by pocupine** [comment]
Hi,
I used GetModesV2 and get the below result:
arloschedule.py
[{'gatewayId': '4R026B7BA7892', 'uniqueId': 'N86RSRS-114-8193457_4R026B7BA7892', 'type': 'activeAutomations', 'activeSchedules': ['schedule.1'], 'schemaVersion': 1, 'activeModes': [], 'timestamp': 1549024963798}]

I then used
arlo.CustomMode(basestations[0], mode=none, schedules=['schedule.1']) and
arlo.CustomMode(basestations[0], schedules=['schedule.1'])
both didn't work.

Any idea why this happened? Thanks.

**Comment by pocupine** [comment]
I also used as Jeff recommended 
arlo.CustomMode(basestations[0], schedules=['schedules.1']) but didn't work.

**Comment by alistairg** [comment]
I'm working through the "'EventStream' object has no attribute 'event_stream_thread'" error when I get it elsewhere. In my case it's caused by Arlo returning a 'logout' event immediately upon subscription, so bad things happen. 

I suspect it's because a prior run of the API crashed, we're retrying quickly, so Arlo tries to terminate the prior connection, but the termination message is sent to the new session. That'd then cause subscription "hangs" as the event subscription was (incorrectly) terminated during "Register"...

I think we can probably disregard that "logout" message *if* registration has not successfully completed. I'll do more tests, and submit a PR if that fixes it.

**Comment by jeffreydwalter** [comment]
That sounds reasonable.

**Comment by jeffreydwalter** [comment]
@alistairg @clorteau don't know if you guys are still using this library, but I did a pretty big rewrite of the eventstream code a while back. Would be interested to know if the latest build fixes your issues.
