### ISSUE TITLE
Support for Arlo Security Lights

### ISSUE THREAD

**Issue by m0urs** [jeffreydwalter/arlo#97]
I would be very happy to see the Arlo Security Lights supported by this module. Especially the possibility to set the armed/disarmed state of the Bridge would be very helpful! Thanks a lot!

**Comment by jeffreydwalter** [comment]
@m0urs I don't own a security light, so it will be up to you to figure that out. I welcome pull requests.

That being said, I would imagine that you'd be able to arm/disarm it using the `Arm()/Disarm()` methods. (See https://github.com/jeffreydwalter/arlo/blob/master/examples/arlo-armdisarm.py)

**Comment by m0urs** [comment]
Unfortunately I am not so an experienced programmer ;-) What I have already seen is that the Bridge seems not to be recognized as a basestation but as a device of type "arlobridge".

So if I do a 

```
# Get the list of devices and filter on device type to only get the basestation.
# This will return an array which includes all of the basestation's associated metadata.
basestations = arlo.GetDevices('basestation')
basestations = basestations + arlo.GetDevices('arlobridge')

```
I can see the bridge as "basestations[1]".

However if I then do a 

`arlo.Arm(basestations[1])`

I get the following error which then I cannot interpret anymore (as I do not really understand the background ;-)):

```
Exception in thread EventStream:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/arlo/Arlo.py", line 295, in QueueEvents
    self.event_streams[basestation_id].Disconnect()
  File "/root/arlo/Arlo.py", line 100, in Disconnect
    self.Unregister()
  File "/root/arlo/Arlo.py", line 120, in Unregister
    if self.heartbeat_thread != threading.current_thread():
AttributeError: 'EventStream' object has no attribute 'heartbeat_thread'
```

**Comment by m0urs** [comment]
I tried now the following and I do not get any error message back. But still the status of the bridge does not change to "armed":

```
from Arlo import Arlo

from datetime import timedelta, date
import datetime
import sys
import json

USERNAME = 'XXXXXXXXXXXXX'
PASSWORD = 'YYYYYYYYYYYYY'

def ArmBridge(self,basestation):
    return self.Notify(basestation, {"action":"set","resource":"modes","publishResponse":True,"properties":{"active":"mode1"}})

def DisarmBridge(self,basestation):
    return self.Notify(basestation, {"action":"set","resource":"modes","publishResponse":True,"properties":{"active":"mode0"}})

try:
        # Instantiating the Arlo object automatically calls Login(), which returns an oAuth token that gets cached.
        # Subsequent successful calls to login will update the oAuth token.
        arlo = Arlo(USERNAME, PASSWORD)
        # At this point you're logged into Arlo.

        # Get the list of devices and filter on device type to only get the basestation.
        # This will return an array which includes all of the basestation's associated metadata.
        basestations = arlo.GetDevices('basestation')
        basestations = basestations + arlo.GetDevices('arlobridge')

        result = ArmBridge(arlo,basestations[1])
        print result

except Exception as e:
    print(e)

```
Result contains something like "web!96669791.289738!1541668748938" which is similar if running the same code against a real basestation (for a real basestation the armed mode is set correctly by this code)

**Comment by jeffreydwalter** [comment]
Hi @m0urs interesting! Haven't seen an arlobridge before.

Can you run the script on this wiki page https://github.com/jeffreydwalter/arlo/wiki/Arlo-Hardware-Schemas and paste the json here please?

**Comment by m0urs** [comment]
```
[
    {
        "arloMobilePlan": false, 
        "dateCreated": 1528092106796, 
        "deviceId": "XXXXXXXXXXXXX", 
        "deviceName": "", 
        "deviceType": "siren", 
        "displayOrder": 1, 
        "lastModified": 1542493434825, 
        "mediaObjectCount": 0, 
        "modelId": "VMB4000-siren", 
        "owner": {
            "firstName": "", 
            "lastName": "", 
            "ownerId": "XXX-XXXXXX"
        }, 
        "parentId": "XXXXXXXXXXXXX", 
        "presignedFullFrameSnapshotUrl": "", 
        "presignedLastImageUrl": "", 
        "presignedSnapshotUrl": "", 
        "state": "provisioned", 
        "uniqueId": "XXX-XXXXXX_XXXXXXXXXXXXX#X", 
        "userId": "XXXXXXX-XXX-XXXXXXXX", 
        "userRole": "ADMIN", 
        "xCloudId": "XXXXXX-XXXX-XXX-XXXXXXXX"
    }, 
    {
        "arloMobilePlan": false, 
        "cvrEnabled": false, 
        "dateCreated": 1529414976584, 
        "deviceId": "XXXXXXXXXXXXX", 
        "deviceName": "", 
        "deviceType": "camera", 
        "displayOrder": 2, 
        "firmwareVersion": "1.125.11.3_26229", 
        "interfaceSchemaVer": "1", 
        "interfaceVersion": "i002", 
        "lastImageUploaded": "true", 
        "lastModified": 1542493434825, 
        "mediaObjectCount": 21, 
        "modelId": "VMC4030P", 
        "owner": {
            "firstName": "", 
            "lastName": "", 
            "ownerId": "XXX-XXXXXX"
        }, 
        "parentId": "XXXXXXXXXXXXX", 
        "presignedFullFrameSnapshotUrl": "", 
        "presignedLastImageUrl": "", 
        "presignedSnapshotUrl": "", 
        "properties": {
            "hwVersion": "H3", 
            "modelId": "VMC4030P", 
            "olsonTimeZone": "Europe/Amsterdam"
        }, 
        "state": "provisioned", 
        "uniqueId": "XXX-XXXXXX_XXXXXXXXXXXXX", 
        "userId": "XXXXXXX-XXX-XXXXXXXX", 
        "userRole": "ADMIN", 
        "xCloudId": "XXXXXX-XXXX-XXX-XXXXXXXX"
    }, 
    {
        "arloMobilePlan": false, 
        "cvrEnabled": false, 
        "dateCreated": 1528092112361, 
        "deviceId": "XXXXXXXXXXXXX", 
        "deviceName": "", 
        "deviceType": "camera", 
        "displayOrder": 3, 
        "firmwareVersion": "1.125.11.3_26229", 
        "interfaceSchemaVer": "1", 
        "interfaceVersion": "i002", 
        "lastImageUploaded": "true", 
        "lastModified": 1542493434826, 
        "mediaObjectCount": 24, 
        "modelId": "VMC4030P", 
        "owner": {
            "firstName": "", 
            "lastName": "", 
            "ownerId": "XXX-XXXXXX"
        }, 
        "parentId": "XXXXXXXXXXXXX", 
        "presignedFullFrameSnapshotUrl": "", 
        "presignedLastImageUrl": "", 
        "presignedSnapshotUrl": "", 
        "properties": {
            "hwVersion": "H3", 
            "modelId": "VMC4030P", 
            "olsonTimeZone": "Europe/Amsterdam"
        }, 
        "state": "provisioned", 
        "uniqueId": "XXX-XXXXXX_XXXXXXXXXXXXX", 
        "userId": "XXXXXXX-XXX-XXXXXXXX", 
        "userRole": "ADMIN", 
        "xCloudId": "XXXXXX-XXXX-XXX-XXXXXXXX"
    }, 
    {
        "arloMobilePlan": false, 
        "cvrEnabled": false, 
        "dateCreated": 1528092617416, 
        "deviceId": "XXXXXXXXXXXXX", 
        "deviceName": "", 
        "deviceType": "camera", 
        "displayOrder": 4, 
        "firmwareVersion": "1.125.11.3_26229", 
        "interfaceSchemaVer": "1", 
        "interfaceVersion": "i002", 
        "lastImageUploaded": "true", 
        "lastModified": 1542493434826, 
        "mediaObjectCount": 26, 
        "modelId": "VMC4030P", 
        "owner": {
            "firstName": "", 
            "lastName": "", 
            "ownerId": "XXX-XXXXXX"
        }, 
        "parentId": "XXXXXXXXXXXXX", 
        "presignedFullFrameSnapshotUrl": "", 
        "presignedLastImageUrl": "", 
        "presignedSnapshotUrl": "", 
        "properties": {
            "hwVersion": "H3", 
            "modelId": "VMC4030P", 
            "olsonTimeZone": "Europe/Amsterdam"
        }, 
        "state": "provisioned", 
        "uniqueId": "XXX-XXXXXX_XXXXXXXXXXXXX", 
        "userId": "XXXXXXX-XXX-XXXXXXXX", 
        "userRole": "ADMIN", 
        "xCloudId": "XXXXXX-XXXX-XXX-XXXXXXXX"
    }, 
    {
        "arloMobilePlan": false, 
        "dateCreated": 1541614084727, 
        "deviceId": "XXXXXXXXXXXXX", 
        "deviceName": "", 
        "deviceType": "lights", 
        "displayOrder": 5, 
        "firmwareVersion": "3.2.51", 
        "interfaceSchemaVer": "2", 
        "interfaceVersion": "i004", 
        "lastImageUploaded": "false", 
        "lastModified": 1542493434826, 
        "mediaObjectCount": 0, 
        "modelId": "AL1101", 
        "owner": {
            "firstName": "", 
            "lastName": "", 
            "ownerId": "XXX-XXXXXX"
        }, 
        "parentId": "XXXXXXXXXXXXX", 
        "presignedFullFrameSnapshotUrl": "", 
        "presignedLastImageUrl": "", 
        "presignedSnapshotUrl": "", 
        "properties": {
            "hwVersion": "4", 
            "modelId": "AL1101", 
            "olsonTimeZone": null
        }, 
        "state": "provisioned", 
        "uniqueId": "XXX-XXXXXX_XXXXXXXXXXXXX", 
        "userId": "XXXXXXX-XXX-XXXXXXXX", 
        "userRole": "ADMIN", 
        "xCloudId": "XXXX-XXXX-XXX-XXXXXXXX"
    }, 
    {
        "arloMobilePlan": false, 
        "automationRevision": 12, 
        "certAvailable": true, 
        "connectivity": {
            "connected": true, 
            "mepStatus": "unknown", 
            "signalStrength": "4", 
            "type": "wifi"
        }, 
        "dateCreated": 1541613738719, 
        "deviceId": "XXXXXXXXXXXXX", 
        "deviceName": "", 
        "deviceType": "arlobridge", 
        "displayOrder": 6, 
        "firmwareVersion": "2.0.1.0_233_142", 
        "interfaceSchemaVer": "2", 
        "interfaceVersion": "i005", 
        "lastModified": 1542493434857, 
        "mediaObjectCount": 0, 
        "migrateActivityZone": false, 
        "modelId": "ABB1000", 
        "owner": {
            "firstName": "", 
            "lastName": "", 
            "ownerId": "XXX-XXXXXX"
        }, 
        "parentId": "XXXXXXXXXXXXX", 
        "presignedFullFrameSnapshotUrl": "", 
        "presignedLastImageUrl": "", 
        "presignedSnapshotUrl": "", 
        "properties": {
            "hwVersion": "ABB1000r1.0", 
            "modelId": "ABB1000", 
            "olsonTimeZone": "Europe/Amsterdam"
        }, 
        "state": "provisioned", 
        "timeZone": "Europe/Amsterdam", 
        "uniqueId": "XXX-XXXXXX_XXXXXXXXXXXXX", 
        "userId": "XXXXXXX-XXX-XXXXXXXX", 
        "userRole": "ADMIN", 
        "xCloudId": "XXXX-XXXX-XXX-XXXXXXXX"
    }, 
    {
        "arloMobilePlan": false, 
        "automationRevision": 206, 
        "connectivity": {
            "connected": true, 
            "mepStatus": "unknown", 
            "type": "ethernet"
        }, 
        "dateCreated": 1528092106834, 
        "deviceId": "XXXXXXXXXXXXX", 
        "deviceName": "", 
        "deviceType": "basestation", 
        "displayOrder": 2, 
        "firmwareVersion": "1.12.0.0_27099", 
        "interfaceSchemaVer": "8", 
        "interfaceVersion": "i007", 
        "lastModified": 1542493434859, 
        "mediaObjectCount": 0, 
        "migrateActivityZone": false, 
        "modelId": "VMB4000", 
        "owner": {
            "firstName": "", 
            "lastName": "", 
            "ownerId": "XXX-XXXXXX"
        }, 
        "presignedFullFrameSnapshotUrl": "", 
        "presignedLastImageUrl": "", 
        "presignedSnapshotUrl": "", 
        "properties": {
            "hwVersion": "VMB4000r3", 
            "modelId": "VMB4000", 
            "olsonTimeZone": "Europe/Amsterdam"
        }, 
        "state": "provisioned", 
        "timeZone": "Europe/Amsterdam", 
        "uniqueId": "XXX-XXXXXX_XXXXXXXXXXXXX", 
        "userId": "XXXXXXX-XXX-XXXXXXXX", 
        "userRole": "ADMIN", 
        "xCloudId": "XXXXXX-XXXX-XXX-XXXXXXXX"
    }
]

```

**Comment by jeffreydwalter** [comment]
@m0urs thank you! From what I understand, the arlobridge is just a wifi extender. I don't think you need to programmatically interact with it. I believe that the light connects to the basestation itself, like the cameras do.

You could try the example from here: https://github.com/jeffreydwalter/arlo/wiki/Arming-and-Disarming-Camera

```
from Arlo import Arlo

USERNAME = 'user@example.com'
PASSWORD = 'supersecretpassword'

try:
	# Instantiating the Arlo object automatically calls Login(), which returns an oAuth token that gets cached.
	# Subsequent successful calls to login will update the oAuth token.
	arlo = Arlo(USERNAME, PASSWORD)
	# At this point you're logged into Arlo.

	# Get the list of devices and filter on device type to only get the basestation.
	# This will return an array which includes all of the basestation's associated metadata.
	basestations = arlo.GetDevices('basestation')

	# Arm Arlo.
	arlo.Arm(basestations[0])
	# Or
	# Disarm Arlo.
	# arlo.Disarm(basestations[0])

except Exception as e:
    print(e)
```

**Comment by m0urs** [comment]
@jeffreydwalter Unfortunately that does not work. You can see in the app also that the lights are connected to the Bridge and not to the basestation like the cameras do.

In the app or the website you can enable / disable the cameras and the lights independently. 

Unfortunately I cannot add JPG or PNG files here. It says that the file type cannot be processed :-( So I uploaded them here:

https://owncloud.urspringer.de/index.php/s/LoRpqJJbsJRDcEo
https://owncloud.urspringer.de/index.php/s/4ykR7RxtJbaMdra

**Comment by jeffreydwalter** [comment]
@m0urs interesting! Would you mind getting me the http traffic between your browser and the arlo servers when you arm/disarm your bridge?

To do this:

1. Use Chrome.
2. Right-click anywhere on the page and choose "Inspect" from the context menu. This will open the developer console.
3. Click on the Network tab.
4. Check the "Preserve log" checkbox.
5. Click the "Clear" icon (it looks like a circle with a slash through it).
6. Arm/Disarm your bridge from the browser.
7. Copy the http requests which show up in the developer console and paste them to me here. Please include the "Request Payload" from the "Headers" tab for each http request.

It will look something like this:
```
{"from":"336-XXXXXXX_web","to":"XXXXXXXXXXXXX","action":"set","resource":"modes","transId":"web!baf3e5e8.a1353!XXXXXXXXXXXXXX","publishResponse":true,"properties":{"active":"mode1"}}
```

You will also see an http request to `https://arlo.netgear.com/hmsweb/client/subscribe`. If you click on that request, you will see an `EventStream` tab. I will also need the events that appear here when you arm/disarm the bridge.
![image](https://user-images.githubusercontent.com/567047/49107649-eb5cda00-f24b-11e8-9f2a-33a16b4eb83f.png)

**Comment by m0urs** [comment]
@jeffreydwalter 

**Arm Bridge:**

```
https://arlo.netgear.com/hmsweb/users/devices/automation/active

{"activeAutomations":[{"deviceId":"59G1865E007ED","timestamp":1543475422648,"activeModes":["mode1"],"activeSchedules":[]}]}

```
**Disarm Bridge:**

```
https://arlo.netgear.com/hmsweb/users/devices/automation/active

{"activeAutomations":[{"deviceId":"59G1865E007ED","timestamp":1543475426862,"activeModes":["mode0"],"activeSchedules":[]}]}

```
**Set Bridge to a custom mode:**

```
https://arlo.netgear.com/hmsweb/users/devices/automation/active

{"activeAutomations":[{"deviceId":"59G1865E007ED","timestamp":1543475617010,"activeModes":["mode3"],"activeSchedules":[]}]}
```
All requests are post requests.

> You will also see an http request to https://arlo.netgear.com/hmsweb/client/subscribe

I only see one such request if I load the page and do not clear the requests before arming/disarming. However in the event stream tab of that requests nothing happens when arming/disarming the bridge. I tested that with arming/disarming the camera hub but also do not see any events here? Maybe I have done something wrong?

BTW: I do now have two bridges already (because the bridges do not have a very good wifi receiver ... So it would be great to support that as well ;-)

**Comment by jeffreydwalter** [comment]
Excellent! Thank you. The good news is that my library already has support for that API. I am going to add some logic to the `Arm()`/`Disarm()` methods so we'll have a common interface.

**Comment by m0urs** [comment]
Great, thank you. Let me know if you want me to test something.

**Comment by jeffreydwalter** [comment]
Please update your arlo package to the latest and try to `Arm()/Disarm()`.

```
from Arlo import Arlo

USERNAME = 'user@example.com'
PASSWORD = 'supersecretpassword'

try:
	# Instantiating the Arlo object automatically calls Login(), which returns an oAuth token that gets cached.
	# Subsequent successful calls to login will update the oAuth token.
	arlo = Arlo(USERNAME, PASSWORD)
	# At this point you're logged into Arlo.

	# Get the list of devices and filter on device type to only get the basestation.
	# This will return an array which includes all of the basestation's associated metadata.
	arlobridges = arlo.GetDevices('arlobridge')

	# Arm Arlo.
	arlo.Arm(arlobridges[0])
	# Or
	# Disarm Arlo.
	# arlo.Disarm(arlobridges[0])

except Exception as e:
    print(e)
```

**Comment by m0urs** [comment]
I do get the following error if trying to arm:

`SetAutomationActive() takes at least 3 arguments (2 given)`

**Comment by jeffreydwalter** [comment]
Oops, sorry about that! Forgot to pass the device object. Try with the latest.

**Comment by m0urs** [comment]
Still another error now:

`'module' object has no attribute 'now'`

**Comment by jeffreydwalter** [comment]
do you get any line numbers or anything?

**Comment by jeffreydwalter** [comment]
Are you running the script I pasted you? That error is usually related to the datetime python module not being imported properly (or the call to now() not being made correctly).

**Comment by m0urs** [comment]
I do not get any line number just that output. I use the script from here: https://github.com/jeffreydwalter/arlo/issues/97#issuecomment-442930890

I also tried to add 

```
from datetime import timedelta, date
import datetime
import sys
```

as in the sample script. But get the same error.

**Comment by jeffreydwalter** [comment]
Are you using this script? 
```
from Arlo import Arlo

USERNAME = 'user@example.com'
PASSWORD = 'supersecretpassword'

try:
	# Instantiating the Arlo object automatically calls Login(), which returns an oAuth token that gets cached.
	# Subsequent successful calls to login will update the oAuth token.
	arlo = Arlo(USERNAME, PASSWORD)
	# At this point you're logged into Arlo.

	# Get the list of devices and filter on device type to only get the basestation.
	# This will return an array which includes all of the basestation's associated metadata.
	arlobridges = arlo.GetDevices('arlobridge')

	# Arm Arlo.
	arlo.Arm(arlobridges[0])
	# Or
	# Disarm Arlo.
	# arlo.Disarm(arlobridges[0])

except Exception as e:
    print(e)
```

**Comment by m0urs** [comment]
> Are you using this script?

Yes, exactly.

**Comment by jeffreydwalter** [comment]
okay, that was my bad! I can't test this code since I don't have an arlobridge. :/

I was calling time.now() instead of datetime.datetime.now().

Give the latest build a try.

Thanks again for your patients!

**Comment by m0urs** [comment]
Now it works! I can arm and disarm. Great! Is there a command to set a certain custom mode as well?

**Comment by jeffreydwalter** [comment]
The method is already there in my library, it's `GetAutomationActive()`, but I'd like to merge it with the `GetModes()` method.

Can you please run `GetAutomationActive()` and send me the output?

**Comment by m0urs** [comment]
```
[{u'activeSchedules': [], u'timestamp': 1543863136369L, u'uniqueId': u'114-183221_4RD3837TA2965', u'gatewayId': u'4RD3837TA2965', u'activeModes': [u'mode1'], u'schemaVersion': 1, u'type': u'activeAutomations'}, {u'activeSchedules': [u'schedule.1'], u'timestamp': 1543862140549L, u'uniqueId': u'114-183221_5631875D01239', u'gatewayId': u'5631875D01239', u'activeModes': [], u'schemaVersion': 1, u'type': u'activeAutomations'}, {u'activeSchedules': [u'schedule.1'], u'timestamp': 1543862138184L, u'uniqueId': u'114-183221_59G1865E007ED', u'gatewayId': u'59G1865E007ED', u'activeModes': [], u'schemaVersion': 1, u'type': u'activeAutomations'}]
```
You can define different modes which you can set manually and you can create schedules where you can define which of your modes will be set at what time.

**Comment by jeffreydwalter** [comment]
@m0urs thanks for that. Just uploaded v1.1.13. I renamed `GetAutomationActive` to `GetActiveModes`.

Thanks again for your help!
Jeff

**Comment by jeffreydwalter** [comment]
@m0urs okay, just did a little cleanup and pushed v1.2.0.

The new API is as follows:
```
    # I don't know if this works for arlobridge or not (this is an old method).
    # If you want to use the developer console to get the http request that's made when you delete an arlo bridge mode, that would be great.
    def DeleteMode(basestation, mode)
    
    # This is the old API for getting modes.
    def GetModes(basestation)

    # This is the newer API for getting modes. It returns the active mode and schedule info.
    def GetModesV2():

    # This is now a combined call that works for both basestations and arlobridges.
    def CustomMode(device, mode, schedules=[])

    # These two have been updated to call CustomMode(), so they should also work for all applicable device types. 
    def Arm(self, device):
    def Disarm(self, device):
```

Please let me know if you find any issues or if there's anything the library needs.

Thanks again,
Jeff

**Comment by m0urs** [comment]
Hi Jeff, 
thank you very much, great work!

That works for me. I can use CustomMode now to set the mode for my lights. Now I only need to get maluk to include that into the module for the FHEM house automation system :-). 

Here the information while I delete a mode of a light:

**Link Address:**

`https://arlo.netgear.com/hmsweb/users/locations/114-183221_5631875D01239/modes/mode3`

**Request:**

`DELETE /hmsweb/users/locations/114-183221_5631875D01239/modes/mode3 HTTP/1.1`

**Response:**

`{"success":true,"data":{"uniqueId":"114-183221_5631875D01239","revision":"30"}}`

**Comment by jeffreydwalter** [comment]
@m0urs I updated the `DeleteModes` method to support arlobridge devices.
